apiVersion: apps/v1
kind: Deployment
metadata:
  name: structurizr-3
  namespace: structurizr-ns-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: structurizr-3
  template:
    metadata:
      labels:
        app: structurizr-3
    spec:
      containers:
        - name: structurizr-3
          image: structurizr/onpremises:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: structurizr-3
  namespace: structurizr-ns-3
spec:
  selector:
    app: structurizr-3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080